# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='NULL', upload_to='images'),
            preserve_default=False,
        ),
    ]
