# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:12
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsweb', '0003_auto_20160228_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
