# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsweb', '0005_remove_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_posts',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='tag_posts',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='newsweb.Tag'),
        ),
        migrations.DeleteModel(
            name='Tag_Posts',
        ),
    ]
