# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsweb', '0007_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='newsweb.Tag'),
        ),
    ]
