# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.Post')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='user_email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tst.Category'),
            preserve_default=False,
        ),
    ]
